# mrtheduts' zshrc

# Path to your oh-my-zsh installation.
export ZSH="/home/mrtheduts/.oh-my-zsh"

# Load icons from nerdfont
POWERLEVEL9K_MODE='nerdfont-complete'

# Set name of the theme to load
ZSH_THEME="powerlevel9k/powerlevel9k"


# Uncomment the following line to automatically update without prompting.
DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=7

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git history sudo)

# Loading oh-my-zsh file
source $ZSH/oh-my-zsh.sh

# Customizing powerlevel9k prompt
PWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context virtualenv dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status battery history)

# Hide default user name
DEFAULT_USER="$USER"

# Hide battery duration
POWERLEVEL9K_BATTERY_VERBOSE=false

# Prompts layout
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="$ "
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# Aliases
alias yt="youtube-viewer"

